import { chromium } from 'playwright'
import { readFileSync } from 'fs'
const state = JSON.parse(readFileSync('/tmp/opencode/bandcamp/storage.json','utf8'))
const browser = await chromium.launch({ headless: true })
const ctx = await browser.newContext()
await ctx.addCookies(state.cookies)
const page = await ctx.newPage()
page.on('console', m => { if (m.type()==='error') console.log('ERR:', JSON.stringify(m.args().map(a=>a.toString().slice(0,300)))) })
await page.goto('https://andra-network.bandcamp.com/edit_album', { waitUntil: 'domcontentloaded' })
await page.locator('input.title.required').fill('SIGNAL DEPTH 2')
await page.locator('ol.tracks li.add-audio input[type=file]').first().setInputFiles('/tmp/opencode/bc-masters/GH_EXT.flac')
await page.waitForTimeout(15000)
const row = page.locator('ol.tracks li.track').first()
console.log('class after 15s:', await row.getAttribute('class'))
const inputs = await row.locator('input').evaluateAll(ns => ns.map(n => ({ tag: n.tagName, cls: n.className, ph: n.getAttribute('placeholder'), name: n.getAttribute('name'), type: n.type })))
console.log('inputs:', JSON.stringify(inputs, null, 0))
const errD = await row.locator('.error-text, .error, .upload-error').allInnerTexts().catch(()=>[])
console.log('err divs:', JSON.stringify(errD))
await page.screenshot({ path: '/tmp/opencode/bandcamp/flac2-row.png' })
await browser.close()
