import { chromium } from 'playwright'
import { readFileSync } from 'fs'
const state = JSON.parse(readFileSync('/tmp/opencode/bandcamp/storage.json','utf8'))
const browser = await chromium.launch({ headless: true })
const ctx = await browser.newContext()
await ctx.addCookies(state.cookies)
const page = await ctx.newPage()
page.on('console', m => { if (m.type()==='error') console.log('ERR:', JSON.stringify(m.args().map(a=>a.toString().slice(0,400)))) })
await page.goto('https://andra-network.bandcamp.com/edit_album', { waitUntil: 'domcontentloaded' })
await page.locator('input.title.required').fill('FLAC PROBE')
await page.locator('ol.tracks li.add-audio input[type=file]').first().setInputFiles('/tmp/opencode/bc-masters/GH_EXT.flac')
console.log('file set, waiting 60s')
await page.waitForTimeout(60000)
const row = page.locator('ol.tracks li.track').first()
const cls = await row.getAttribute('class').catch(()=>'none')
console.log('row class:', cls)
const err = await row.locator('.error, [class*="error"], .message').allInnerTexts().catch(()=>[])
console.log('row error texts:', JSON.stringify(err))
const txt = (await row.innerText().catch(()=>'')).slice(0,200)
console.log('row text:', JSON.stringify(txt))
await page.screenshot({ path: '/tmp/opencode/bandcamp/flac-probe.png' })
await browser.close()
