import { chromium } from 'playwright'
import { readFileSync } from 'fs'
const state = JSON.parse(readFileSync('/tmp/opencode/bandcamp/storage.json','utf8'))
const browser = await chromium.launch({ headless: true })
const ctx = await browser.newContext()
await ctx.addCookies(state.cookies)
const page = await ctx.newPage()
page.on('console', m => { if (m.type()==='error') console.log('ERR:', m.text().slice(0,300)) })
page.on('dialog', async d => { console.log('DIALOG:', d.type(), d.message().slice(0,200)); await d.dismiss().catch(()=>{}) })
const log = (...a) => console.log(new Date().toISOString().slice(11,19), ...a)
await page.goto('https://andra-network.bandcamp.com/edit_album?id=781157310', { waitUntil: 'domcontentloaded' })
await page.waitForTimeout(2500)
const price = page.locator('input[name="album.price"]').first()
await price.click()
await price.press('Control+A')
await price.type('27', { delay: 40 })
log('album price set:', await price.inputValue())
const saveBtn = page.locator('[data-test="save-draft-button"]').first()
await saveBtn.click()
log('save clicked; waiting...')
await page.waitForTimeout(4000)
log('url after save:', page.url())
await page.screenshot({ path: '/tmp/opencode/bandcamp/pub-before-publish.png' })
const pub = page.locator('a.publish[data-test="publish-tralbum"]').first()
log('publish text:', (await pub.innerText().catch(()=>''))?.trim(), 'visible:', await pub.isVisible().catch(()=>false), 'enabled:', (await pub.getAttribute('class').catch(()=>''))?.includes('disabled')===false)
await pub.click()
log('publish clicked; waiting...')
await page.waitForTimeout(6000)
log('url after publish:', page.url())
const body = await page.locator('body').innerText().catch(()=>'')
const hasErr = /error|must|need|regis|sold|pay|account|tos|terms|limit/i
const lines = body.split('\n').map(s=>s.trim()).filter(s=>s && (s.length<140) && hasErr.test(s)).slice(0,12)
log('notable body lines:', JSON.stringify(lines))
await page.screenshot({ path: '/tmp/opencode/bandcamp/pub-after-publish.png', fullPage: true })
await browser.close()
log('DONE url=', page.url())
